### ISSUE TITLE
tvOS TestFlight 1.0.15(8)  播放器bug

### ISSUE THREAD

**Issue by dukoalad** [alexiscn/fileball.app#3]
tvOS TestFlight 1.0.15(8) 版本
实验室-测试播放器 开启

播放emby 时，音频正常，画面一直抖动，跳着抖动；

关闭测试播放器，播放恢复正常；

**Comment by alexiscn** [comment]
已知问题，还不知道怎么修复；另外无字幕也是已知问题

**Comment by dukoalad** [comment]
目前上的这个测试播放器也是mpv ？

**Comment by alexiscn** [comment]
> 目前上的这个测试播放器也是mpv ？

是的
